"""new fields in user model

Revision ID: 967662a296f2
Revises: 38733e6dbe91
Create Date: 2018-05-16 11:00:26.404079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967662a296f2'
down_revision = '38733e6dbe91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
